apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cofide-connect.fullname" . }}
  labels:
    {{- include "cofide-connect.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "cofide-connect.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "cofide-connect.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "cofide-connect.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Release.Name }}
          envFrom:
          - configMapRef:
              name: {{ include "cofide-connect.fullname" . }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          livenessProbe:
            grpc:
              port: 51106
            initialDelaySeconds: 10
            periodSeconds: 15
            failureThreshold: 3
            timeoutSeconds: 5
          readinessProbe:
            grpc:
              port: 51106
            initialDelaySeconds: 10
            periodSeconds: 15
            failureThreshold: 3
            timeoutSeconds: 5
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: spiffe-workload-api
              mountPath: /spiffe-workload-api
            - name: sqlite-data
              mountPath: "/app/data"
        - name: envoy-sidecar
          image: {{ .Values.envoy.image }}
          command: ["envoy"]
          args:
            - -c
            - /etc/envoy/envoy.yaml
            - --service-node
            - ${POD_NAME}
            - --service-cluster
            - ${POD_NAMESPACE}
            - -l
            - {{ .Values.envoy.logLevel }}
          ports:
            - name: https
              containerPort: 8443
            - name: admin
              containerPort: 9901 
          volumeMounts:
            - name: envoy-config
              mountPath: /etc/envoy
            - name: spiffe-workload-api
              mountPath: /spiffe-workload-api
            - name: envoy-tls
              mountPath: /etc/envoy/tls
              readOnly: true
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          {{- with .Values.envoy.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.envoy.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: spiffe-workload-api
          csi:
            driver: "csi.spiffe.io"
            readOnly: true
        - name: envoy-config
          configMap:
            name: connect-api-envoy-config
        - name: envoy-tls
          secret:
            secretName: {{ .Values.envoy.auth.tlsSecretName }}
        - name: sqlite-data
          hostPath:
            path: /app/data
            type: DirectoryOrCreate
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
